README.md: workaround for the cargo manpage issue
tummychow/git-absorb pull request #40
Opened 2021-04-14 09:21 UTC by gasche

git-absorb provides a manpage, but cargo does not currently know how to install it.
Offer a manual workaround in the README.

2021-04-14 10:16 UTC, waldyrious commented on README.md
> +Note: `cargo install` does not currently know how to install manpages ([cargo#2729](https://github.com/rust-lang/cargo/issues/2729)), so if you use `cargo` then `git absorb --help` will not work. Her
A minor tweak:

```suggestion
Note: `cargo install` does not currently know how to install manpages ([cargo#2729](https://github.com/rust-lang/cargo/issues/2729)), so if you use `cargo` for installation then `git absorb --help` will not work. Here is a manual workaround, assuming your system has a `~/.local/share/man/man1` directory that `man --path` knows about:
```

2021-04-14 10:40 UTC, gasche commented on README.md
> +Note: `cargo install` does not currently know how to install manpages ([cargo#2729](https://github.com/rust-lang/cargo/issues/2729)), so if you use `cargo` then `git absorb --help` will not work. Her
Thanks!

2021-04-21 02:43 UTC, tummychow requested changes

2021-04-21 02:43 UTC, tummychow commented on README.md
> +wget https://github.com/tummychow/git-absorb/blob/master/Documentation/git-absorb.1
i don't think this actually works? you need the raw link right

2021-04-21 05:24 UTC, gasche commented on README.md
> +wget https://github.com/tummychow/git-absorb/blob/master/Documentation/git-absorb.1
Ah, my bad. I did the mistake on my machine, then fixed the link, but I copied the old steps...
This is now fixed, thanks for the catch!

2021-04-21 08:03 UTC, merged