Add feature to generate one fixup per commit.
tummychow/git-absorb pull request #91
Opened 2023-07-21 15:57 UTC by rbartlensky

This is my attempt at implementing the feature request from #19.

I would suggest reviewing the changeset commit by commit, since I made sure to split the work into logical chunks: refactor, add feature, tests, and so on.

Closes issue #19.

2023-07-21 20:31 UTC, tummychow requested changes
sorry that my primary feedback is "i disagree with the structure of the refactor", i know that's the most annoying sort of feedback i could have given.

2023-07-21 20:31 UTC, tummychow commented on src/lib.rs
> +                    head.create_fixup_for(&repo, dest_commit)?;
i think the entire `Head` struct is pretty superfluous. yes it deduplicates code between this call site and the later call site, but it would be better to rearrange the code so that there's only one call site in the first place. the only mutable state that's truly necessary here is the tree (as before) and the mapping of hunks-being-committed to commits-being-fixed-up.

let me see if i can explain the procedure. what you have is: "if we're making one fixup per commit, then remember this hunk for later, otherwise commit it immediately. then at the end, we iterate over the hunks we remembered, and combine them into commits". instead, i would do: "remember every hunk regardless of whether we're making one fixup per commit, then at the end, apply hunks to the tree while making commits according to the desired behavior".

i think this approach reduces the boilerplate of introducing an additional structure and also moves all the mutative behavior into a single place (which could later be moved to its own function for testing, but that's not required for this pr). for the record, i don't care about preserving the order of fixups (ie the final implementation of this feature should still support one-hunk-per-commit behavior, but it doesn't have to produce those commits in the same order as the code on master) nor do i care about preserving the order of logs (ie it's fine to do all the commutation analysis and then do all the commit application, even when making one hunk per commit, as opposed to the behavior on master where those logs are interleaved). both of those are implementation details of git-absorb since they have no effect on the outcome after rebasing.

2023-07-21 20:31 UTC, tummychow commented on src/lib.rs
> +              "header" => format!("+{},-{})", added, removed),
can we compute this from diffing the trees (repository::diff_tree_to_tree), rather than having to track it with shared counters?  i always prefer having less mutable state, especially when mixed between multiple functions

2023-07-21 20:31 UTC, tummychow commented on src/lib.rs
> +        let dir = tempfile::tempdir().unwrap();
ah, thank you for this. e2e testing has been on the todo list since forever. i would prefer to use the mempack odb backend for repos generated in tests, but the api is pretty esoteric and i'm not sure how well it's supported by upstream, so i won't ask you to figure that out.

2023-07-22 23:15 UTC, rbartlensky commented on src/lib.rs
> +                    head.create_fixup_for(&repo, dest_commit)?;
I did my best to retain the old logic, and I do agree that it's much easier to implement it the way you suggested if we stop caring about the ordering of fixups and such. I really appreciate the detailed response!

2023-07-22 23:17 UTC, rbartlensky commented on src/lib.rs
> +              "header" => format!("+{},-{})", added, removed),
I wanted to avoid a potentially expensive operation (such as diffing two trees), but I don't have a good reason not to do it (I haven't measured anything!)

2023-07-22 23:26 UTC, rbartlensky commented on src/lib.rs
> +        let dir = tempfile::tempdir().unwrap();
oh that is interesting, I want to try it out now! (if it takes too long I can open an issue for it and follow up with another PR)

2023-07-23 00:16 UTC, rbartlensky commented on src/lib.rs
> +                    head.create_fixup_for(&repo, dest_commit)?;
The last two commits should do the trick. I will squash away the revert and the refactoring once you're happy with the changes.

2023-07-23 00:17 UTC, rbartlensky commented on src/lib.rs
> +              "header" => format!("+{},-{})", added, removed),
See https://github.com/tummychow/git-absorb/pull/91/commits/142467011affe88e557226e7963eeee50f640984#diff-b1a35a68f14e696205874893c07fd24fdb88882b47c23cc0e0c80a30c7d53759R277-R279

2023-07-23 00:18 UTC, rbartlensky commented on src/lib.rs
> +        let dir = tempfile::tempdir().unwrap();
I haven't looked into this yet, but I will once I know the other parts are OK

2023-07-23 01:17 UTC, tummychow requested changes
thanks, that's the arrangement i had in mind

2023-07-23 01:17 UTC, tummychow commented on src/lib.rs
> +        // head.apply_hunk_to_tree(&repo, &current.hunk_to_apply, &current.index_patch.old_path)?;
nit: lingering comment?

2023-07-23 01:17 UTC, tummychow commented on src/lib.rs
> +        let fixup_complete = || match next {
stylistic preference: i would use option::map_or, rather than writing out the full match statement and then having to wrap it in a closure for brevity. i would even check config.one_fixup_per_commit inside the map_or closure, but i have perhaps a stronger preference for combinators than is typical

2023-07-23 01:17 UTC, tummychow commented on src/lib.rs
> +                .diff_tree_to_tree(Some(&head_tree), None, None)?
i think the second argument being `None` is not what you want? that diffs against an empty tree, you need the tree of the current head_commit

2023-07-23 01:17 UTC, tummychow commented on src/lib.rs
> +        head_tree = apply_hunk_to_tree(
huh yknow, it occurs to me now that creating trees is technically pointless in dry run mode. ah well, that's a problem for git gc

2023-07-23 01:17 UTC, tummychow commented on src/lib.rs
> +fn commit_locator<'c>(
stylistic preference: this function is now only called once, so i would inline it back into the call site like it was originally. you can also remove the additional imports after that

2023-07-25 19:39 UTC, rbartlensky commented on src/lib.rs
> +        // head.apply_hunk_to_tree(&repo, &current.hunk_to_apply, &current.index_patch.old_path)?;
yes!

2023-07-25 19:40 UTC, rbartlensky commented on src/lib.rs
> +                .diff_tree_to_tree(Some(&head_tree), None, None)?
how about now? It does seem to be more readable I agree

2023-07-25 19:40 UTC, rbartlensky commented on src/lib.rs
> +fn commit_locator<'c>(
done

2023-07-25 19:40 UTC, rbartlensky commented on src/lib.rs
> +        let fixup_complete = || match next {
how about now? It does seem to be more readable I agree

2023-07-25 21:13 UTC, tummychow requested changes
lgtm other than this last comment. let me know if you still want to try mempack on this pr, otherwise i'll merge after this one is addressed

2023-07-25 21:13 UTC, tummychow commented on src/lib.rs
> +                .diff_tree_to_tree(Some(&current.dest_commit.tree()?), Some(&head_tree), None)?
hm, instead of dest_commit, i think you need head_commit here. eg if you imagine you have this arrangement:

```
* commit that modifies foo
|
* commit that modifies bar
|
* ...
```

and you have a fixup being absorbed into bar, you get this commit structure:

```
* fixup! bar
|
* commit that modifies foo
|
* commit that modifies bar
|
* ...
```

you're diffing between the fixup and the bar commit, so the resulting header also includes the delta of the foo commit.

2023-07-25 21:14 UTC, tummychow commented
oh and also, the new test is failing so you'll have to figure out what's going on there. looks like something trivial related to the new repo having no configured user

2023-07-25 21:39 UTC, rbartlensky commented on src/lib.rs
> +                .diff_tree_to_tree(Some(&current.dest_commit.tree()?), Some(&head_tree), None)?
good catch! that was not what I meant to do (and my tests didn't catch it either because I was only testing with commits that are next to each other :facepalm:)

2023-07-25 21:40 UTC, rbartlensky commented
@tummychow I squashed away the commits to clean the history up a bit. I think I will follow-up with improving the tests since it's taking longer than I expected

2023-07-25 21:45 UTC, rbartlensky commented
Also thank you for the quick turnaround!

2023-07-25 21:52 UTC, tummychow commented
no problem, thanks for implementing all the requested changes

2023-07-25 21:52 UTC, merged

2023-08-20 16:52 UTC, nickolay commented
Thanks for implementing this feature! Any reason the new `-F` mode is not the default?

2023-08-20 17:53 UTC, rbartlensky commented
> Any reason the new `-F` mode is not the default?

There's an explanation in the first commit message:

> In order to not break the workflow of others, we choose to make this
an option rather than the default. Moreover, folks can `alias
git-absorb="git-absorb --one-fixup-per-commit"` if they wish to always
use this option, and not have to type it out.

I will let @tummychow decide whether it should become the default in a later release or not.

2023-08-21 00:40 UTC, tummychow commented
yeah i want to let it bake for a while, given the amount of code getting moved around. i would accept a pr to add a git config option for it though